### ISSUE TITLE
maximum does not seem to work with `cupy.array_api`

### ISSUE THREAD

**Issue by OmarManzoor** [data-apis/array-api-compat#160] opened 2024-07-11 09:25 UTC
It seems that the function `maximum` is currently not available for `cupy.array_api`. It is present in the array api specification [maximum](https://data-apis.org/array-api/latest/API_specification/generated/array_api.maximum.html) and works for the other apis. Could this be made compatible for `cupy.array_api` as well?

**Comment by lucascolley** [comment] 2024-07-11 09:29
Hey @OmarManzoor , this is a duplicate of gh-127. `maximum` was added to the standard in the 2023.12 version, and work on that is still in progress.

**Comment by OmarManzoor** [comment] 2024-07-11 09:35
@lucascolley Thanks for the feedback!

**Closed** 2024-07-11 09:38 UTC

**Comment by asmeurer** [comment] 2024-07-15 21:14
What version of CuPy are you using? `cupy` has the `maximum` function https://docs.cupy.dev/en/latest/reference/generated/cupy.maximum.html. array_api_compat.cupy is just an extension of what is already in cupy, so if something is already in cupy there is nothing to do here. 

Note that there is a difference between array_api_compat (this repo) and cupy.array_api. cupy.array_api is the cupy version of `numpy.array_api`, which has been removed from numpy in NumPy 2.0 and renamed to [array-api-strict](https://data-apis.org/array-api-strict/). `cupy.array_api` should not be used, unless you specifically need to test array API strictness with device support (see also https://github.com/data-apis/array-api-strict/issues/5).

**Comment by asmeurer** [comment] 2024-07-16 18:20
This may also be useful to understand the difference https://data-apis.org/array-api-compat/#difference-between-array-api-compat-and-array-api-strict

**Comment by OmarManzoor** [comment] 2024-07-18 09:04
Thank you for the clarifications.
